matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: yoMIxYl0+ji/GUwxBZVi2+Y50wYfRYfsWVqZ8O7e3J6fUXGbQn6E/xn1P3JtH738/+O59d/I6k9F5EatO8HdBip3H9wqjOSws/74IhLTZcu7HeCjjko9o0Rdy46lzP+Q652/65cyee2AyHRR4vYoUdBvQMuAfS7TzlbMdfxM+LYUI9cXp5b6LHZTCFuXraOzsWg8LKvR0zH7bOykEdGhSn8soZozfrQP51yKKRECX91eQrNDIfdHuwqlTnpxwT0rSyXugf6f6SSea6t5blOsgaFTdgWtQrq+m5T51hGLFiC8r/CKFofU54XIVfMn9emSku3RMpTp6mDLcDhqC0ui7pBneWZ6gVtGsiaPQHGBjcjBAjLNJFJ51Q5X6uB+LRaFSwK0+c6TJyC3c90mwnRFj9eMSF0ifWcCnFXX3dVteJsLOrH0MB9ZDOvpuWBGMbcmT+s8esdUbO0zGGLaN2o/Yvv/vLEaVTwAt03abHnNI7qHSc3ItOBGfoRn6jyZb93dcCaCkU0E4VCK9LvJZrxuK+rBfVXJj94oJhlj3dRqs47ehuQchR+6JBXHB9W1sYZLz7F8i9LTy8gZDKtadLBZvMWrmmfs/pvj334t/OB7vXV2YX6YSTidPVAXylhbe7I9XzrR6vYnFR/71FbkNZN9iuwsS3wSkK4JgqTT2AllKIw=
